# Generated by Django 2.0.9 on 2019-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190421_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='webshopprofile',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
