# Generated by Django 2.0.9 on 2019-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_webshopprofile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshopprofile',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
