# Generated by Django 2.0.9 on 2019-04-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190422_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshopprofile',
            name='link',
            field=models.CharField(default='link', max_length=255),
        ),
    ]
