# Generated by Django 2.0.9 on 2019-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190422_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshopprofile',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
