# Generated by Django 2.0.9 on 2019-05-11 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190422_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='webshopprofile',
            name='merchant_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
