# Generated by Django 2.0.9 on 2019-05-26 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_webshopprofile_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjaprofile',
            name='supported_project',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
