# Generated by Django 2.0.9 on 2019-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ninjaprofile_supported_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshopprofile',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
