# Generated by Django 2.0.9 on 2019-05-27 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190521_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_preface',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
